name: Builder

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install JDK.
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Checkout code.
        uses: actions/checkout@v2
      - name: Maven clean install
        run: mvn clean install --file pom.xml
      - name: List target files.
        run: |
         cd target
      - name: Create ssh file.
        uses: "finnp/create-file-action@1.0.0"
          env:
            FILE_NAME: "priv"
            FILE_DATA: ${{ secrets.COM_RSA_SECRET }}
      - name: Set ssh file permissions:
        run: chmod 600 priv
      - name: Stop pulse.
        run: |
         ssh root@74.207.229.78 -i priv
         screen -d pulse
         stop
         exit
      - name: Upload new build.
        run: |
         sftp root@74.207.229.78 -i priv
         cd /home/pulse/pulse
         put Pulse.jar
         exit
      - name: Start pulse.
        run: |
         ssh root@74.207.229.78 -i priv
         screen -R pulse
         cd /home/pulse/pulse
         java -jar Pulse.jar
