name: Builder

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install JDK.
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Checkout code.
        uses: actions/checkout@v2

      - name: Maven clean install
        run: mvn clean install --file pom.xml

      - name: List target files.
        run: |
          cd target
          ls

      - name: Stop pulse.
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: 74.207.229.78
          user: root
          key: ${{ secrets.COM_RSA_SECRET }}
          script: screen -XS pulse quit

      - name: Upload new build.
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          server: 74.207.229.78
          username: root
          ssh_private_key: ${{ secrets.COM_RSA_SECRET }}
          local_path: ./target/Pulse.jar
          remote_path: /home/pulse/Pulse.jar

      - name: Start pulse.
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: 74.207.229.78
          user: root
          key: ${{ secrets.COM_RSA_SECRET }}
          script: cd /home/pulse/Pulse.jar && screen -S pulse -dm ./start.sh
